# -*- coding: utf-8 -*-
"""rps

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C_rCpglFTHxf4XKWa_4_72Z6EiLpYORa
"""

playerOne = input("What would you like to choose? Rock, Paper, or Scissors: ")
gameOutcome = 0
if (playerOne!= 'rock' and playerOne!= 'paper' and playerOne!= 'scissors'):
  print("The option that you typed is not a valid choice. Please type a valid option.")
  gameOutcome = 1
if gameOutcome == 0:
  playerTwo = input("What would you like to choose? Rock, Paper, or Scissors: ")
  if (playerTwo!= 'rock' and playerTwo!= 'paper' and playerTwo!= 'scissors'):
    print("The option that you typed is not a valid choice. Please type a valid option.")
    gameOutcome = 1
if (playerOne == playerTwo):
  print("The game is tied because both players picked the same option.")
elif (playerOne == "paper" and playerTwo == "rock"):
  print("Winner: Player One")
elif (playerOne == "paper" and playerTwo == "scissors"):
  print("Winner: Player Two")
elif (playerOne == "rock" and playerTwo == "paper"):
  print("Winner: Player Two")
elif (playerOne == "rock" and playerTwo == "scissors"):
  print("Winner: Player One")
elif (playerOne == "scissors" and playerTwo == "paper"):
  print("Winner: Player One")
elif (playerOne == "scissors" and playerTwo == "rock"):
  print("Winner: Player Two")